'use strict';var ndjsStaticVersion="sync-1",nsqsjnisez={};function nsmnuq(a,b){if(0<nsuhbmki(a)){var c=nsihscpgih(b);0===nsuhbmki(c)&&(c=document.getElementsByTagName("form"));a.hasOwnProperty("sid")&&null==a.sid&&(a.sid="");a=nsqsjni.stringify(a);nsoednk.hasOwnProperty("pageModeConfig")&&!0===nsoednk.pageModeConfig.encodeData&&(a=nsihsc(a));nswaqszd(c,nsnevf,a);nsuhbmkie(b)}}
function getEnabledEvents(){if(null!==nsqsjnis)return nsqsjnis;var a=nds.getListeners();nsqsjnis={};if(NDS_LISTEN_NONE in a)return nsqsjnis;var b=a.hasOwnProperty(NDS_LISTEN_ALL),c;for(c in nsxss)if(b||a.hasOwnProperty(c))for(var e=!0===b?a[NDS_LISTEN_ALL]:a[c],f=nsxss[c],q=0;q<f.length;q++)nsqsjnis[f[q]]=e;return nsqsjnis}var nsktzqy={},nsnev;
function nsoednkck(a){var b={};b[nsyajtsqee]={};var c;for(c in a)if(a.hasOwnProperty(c)){var e=a[c];"sid"===c&&c in nsyajts.pmd||"wt"===c||"gzrq"===c?b[c]=e:c in nsyajts.pmd&&(b[nsyajtsqee][c]=e)}nsyajts.hasOwnProperty("pmd")&&"fmid"in nsyajts.pmd&&(b.fmid="nds-pmd");return b}var nsktzq=-1,nsnevfo=-1,nsoednkc={},nsoednk={},nsqsjnise={},nsyajts={};
function nsfvxu(a){var b="",c=[41,8,49,48,51,44,63,0,19,61,43,63,57,15,34,6,42,59,41,19,10,45,54,0,44,34,57,36,48];if("BNDX:"===a.substring(0,5)){a=a.substring(5);a=(new TextDecoder).decode(base64ToBytes(a));a=a.substring(4);var e=!0}else e=!1,b="NDX:";for(var f=0,q=0;q<a.length;q+=1){var u=a.charCodeAt(q)-32;0<=u&&94>u&&(e&&64>u&&(u^=c[f%c.length]),u+=47+(e?-1:1)*f*31,u=(u%94+94)%94,!e&&64>u&&(u^=c[f%c.length]),f++);b+=String.fromCharCode(u+32)}return e?b:"BNDX:"+bytesToBase64((new TextEncoder).encode(b))}
var nsktzqytgf={},nsnevfos=[];function nstybxexxx(a,b){return a==b?!0:!1}var nsmnuqjcsi=!1,nsoed="default",nscchy=null,nsqsjnis=null,nds=window.ndsapi||(window.ndsapi={}),nsxsswr=null,nsmnuqjcs=null,ndsMlocTimeoutMs=2E3,numQueries=0,returned=[],version="null";"{@VERSION@}"!==ndjsStaticVersion&&(version=ndjsStaticVersion);function nstybx(a){for(var b=[],c=0;c<a.length;c++)-1===b.indexOf(a[c])&&b.push(a[c]);return b}var ndsWidgetVersion="2.5.3",nsqsjn;
function bytesToBase64(a){a=Array.from(a,function(b){return String.fromCodePoint(b)}).join("");return btoa(a)}var nsyajtsq="NDSASESS";function nsihs(){return window.innerWidth?window.innerWidth:document.documentElement&&document.documentElement.clientWidth?document.documentElement.clientWidth:document.body&&document.body.clientWidth?document.body.clientWidth:null}var nscchylsez="3600",nsxssw="ndsi"+ndjsStaticVersion;
function nsfvxueymy(){var a="";if(window._phantom||window.callPhantom||window.__phantomas)a+="p";window.Buffer&&(a+="n");window.emit&&(a+="c");window.spawn&&(a+="r");window.webdriver&&(a+="s");if(window.domAutomation||window.domAutomationController)a+="b";return a}var nsyajtsqe="ndsid",nsnevf="nds-pmd";function nsihscp(a,b){nsoednkc[a]=b}var nsyajtsqee="widgetData",nsoedn=[];function nscsbbo(a){for(var b in a)if(a.hasOwnProperty(b)){var c=a[b];c&&c.call&&c.apply&&(a[b]=function(){})}}
var nsyajt={addCallback:function(){},callAllCallbacks:function(){}},nsxsswrsy=function(a,b){},nsnevfosj=function(){var a=new Date;return"ndsa"+Math.random().toString(36).substr(2,16)+a.getTime().toString(36)};function nsulvzxx(a){return"[object Array]"===Object.prototype.toString.apply(a)}
var nsmnuqj=function(){for(var a=0,b=document.domain,c=b.split("."),e="_temp"+(new Date).getTime();a<c.length-1&&-1===document.cookie.indexOf(e+"\x3d"+e);)b=c.slice(-1-++a).join("."),document.cookie=e+"\x3d"+e+";domain\x3d"+b+";";document.cookie=e+"\x3d; expires\x3dThu, 01 Jan 1970 00:00:01 GMT; domain\x3d"+b+";";return b};function base64ToBytes(a){a=atob(a);return Uint8Array.from(a,function(b){return b.codePointAt(0)})}nsxsswrs&&(ndwts=function(){});
nds.load=function(a){if(nsxsswrs)nscsbbo(nds),nscsbbo(nds.common),nscsbbo(nds.common.util),nds.send=function(g){"function"===typeof g&&g()};else{var b=function(g){var h={},m;g=g.split("\x26");var v=0;for(m=g.length;v<m;v++){var y=g[v].split("\x3d");h[y[0]]=decodeURIComponent(y[1])}return h},c=a.split("?");nds.config.queryParams=1<c.length?b(c[1]):{};"undefined"===typeof nsqsjn&&(nsqsjn=c=c[0].replace(/\/sync\/js\/?$/,""));c=nsqsjn;var e=function(g){g=nswaq(g);for(var h in g)g.hasOwnProperty(h)&&!g[h]&&
delete g[h];h=nsqsjni.stringify(g);h=nsihsc(h);return"q\x3d"+encodeURIComponent(h)},f=function(g){return(returned.length===u||-1<returned.indexOf(!1))&&"function"===typeof g?(g(),0>returned.indexOf(!1)&&(returned=[]),!0):!1};nds.getQueryArray=function(g){var h=[];"string"===typeof g&&""!==g&&(h=nsjmlppts(g));g=h.length;for(var m=[],v=0;v<g;v++){var y=nsihsc(h[v]);m.push(y)}return m};nds.config.sendTimeout=5E3;nds.send=function(g){nstybxexx("precomplete");if(!0===nsoednk.eventModeEnabled){returned=
[];!1===nsmnuqjcsi&&setTimeout(nds.init,0);!0===nsoednk.ndsidConfig.enable&&nsuhbm();var h=nds.getQueryArray("c");u=h.length;for(var m=0;m<u;m++)(function(){var v="q\x3d"+encodeURIComponent(h[m]),y=new Image,n=null;y.onerror=function(){returned.push(!1);!0===f(g)&&(g=null)};y.onload=function(){n&&clearTimeout(n);returned.push(!0);!0===f(g)&&(g=null)};nds.config.sendTimeout&&(n=setTimeout(y.onerror,nds.config.sendTimeout));y.src=c+"/complete/gif/?"+v})()}else"function"===typeof g&&g();nds.ndwtr()};
nds.loadScript=function(g,h,m){var v=document.getElementById(h);v&&v.parentNode.removeChild(v);v=document.createElement("script");v.setAttribute("type","text/javascript");v.setAttribute("src",g);v.setAttribute("id",h);nds.config.hasOwnProperty("cspNonce")&&0<nds.config.cspNonce.length&&v.setAttribute("nonce",nds.config.cspNonce);g=document.getElementsByTagName("script")[0];g.parentNode.insertBefore(v,g);"function"===typeof m&&m(v)};nds.config.sessionId=null;nsjmlp(nds.config.q);null===nds.config.sessionId&&
("undefined"!==typeof window.ndovStandaloneWidget?nds.config.sessionId=nsjmlpptsb(nsyajtsq):!0===nsoednk.ndsidConfig.enable&&(nsxsswr=nsjmlpptsb(nsyajtsqe),nstybxe(nsxsswr)));nds.init=function(){nsyajt.callAllCallbacks();if("application/json"===nsoed)try{var g=null;null!=XMLHttpRequest&&(g=new XMLHttpRequest);!0===nsoednk.ndsidConfig.enable&&nsuhbm();g.open("GET",c+"/init/js/?"+e("i"));g.setRequestHeader("Cache-Control","max-age\x3d0");g.setRequestHeader("Content-Type","application/json");g.send();
g.onreadystatechange=function(){if(4===g.readyState&&200===g.status)try{var h=JSON.parse(g.response);ndwti(h)}catch(m){}}}catch(h){}else!0===nsoednk.ndsidConfig.enable&&nsuhbm(),nds.loadScript(c+"/init/js/?"+e("i"),nsxssw);nsmnuqjcsi=!0;!0===nsulvzxx(nds.config.initCallbackList)&&nsuhbmkiec(nds.config.initCallbackList,function(h){h()})};nds.reinit=function(g,h,m){null!=g&&nds.setPlacement(g);h&&nds.setPlacementPage(h);m&&(nsqsjnisez.ipr.fm=m);nsfvxuey();nstybxexx("init");nswaqszdc([]);nsnevfos&&0!==
nsnevfos.length?l(nsnevfos):!0===nds.config.isLocationProcessingEnabled&&null===nsmnuqjcs?setTimeout(function(){nds.init()},ndsMlocTimeoutMs):nds.init()};if(nsyajts.hasOwnProperty("id")&&0<nsuhbmki(nsyajts.id)){returned=[];!0===nsoednk.ndsidConfig.enable&&nsuhbm();a=nsjmlppts("id");var q=null,u=a.length;for(b=0;b<u;b++){var C=nsihsc(a[b]);C="rr\x3dsomething\x26q\x3d"+encodeURIComponent(C);var z=new Image;z.onerror=function(){returned.push(!1);!0===f(cb)&&(cb=null)};z.onload=function(){q&&clearTimeout(q);
returned.push(!0);!0===f(cb)&&(cb=null)};nds.config.sendTimeout&&(q=setTimeout(z.onerror,nds.config.sendTimeout));z.src=c+"/init/gif/?"+C}}var l=function(g){nsyajt.callAllCallbacks();nsyajt=nds.common.createCallbackList();var h=-1;var m=nsjmlpp(g);for(g=0;g<m.length;g++)try{var v=m[g];var y=nds.common.addEventListener(v,"focus",nds.init);nsyajt.addCallback(y);h++}catch(n){}-1<h&&nsulv(m,nds.init);-1===h&&(!0===nds.config.isLocationProcessingEnabled&&null===nsmnuqjcs?setTimeout(function(){nds.init()},
ndsMlocTimeoutMs):nds.init())};null==nsnevfos||0===nsnevfos.length?!0===nds.config.isLocationProcessingEnabled&&null===nsmnuqjcs?setTimeout(function(){nds.init()},ndsMlocTimeoutMs):nds.init():l(nsnevfos)}};function nsulv(a,b){var c=10,e=setInterval(function(){for(var f=0;f<a.length;f+=1)try{var q=a[f];if(q&&q.value&&q.value!==q.defaultValue){b();clearInterval(e);return}}catch(u){}--c;1>c&&clearInterval(e)},250);nsyajt.addCallback(function(){clearInterval(e)})}
function nswaq(a){var b={r:Math.floor(1E6*Math.random())+1E3,sid:nds.config.sessionId,p:nsfvxueymy(),bd:nsihscpg(),forceIP:nds.config.forceIP,dtrk:nds.config.doNotTrack,jsv:version,wt:"",wv:ndsWidgetVersion};nsoednk.gzrq&&(b.gzrq=1);switch(a){case "i":b.ls={};try{var c=window.localStorage.getItem("ndcd");null!=c&&(b.ls.ndcd=c)}catch(e){}break;case "c":nsktzqy.hasOwnProperty("wt")&&(b.wt=nsktzqy.wt);break;case "pmd":nsktzqy.hasOwnProperty("sid")&&(b.sid=nsktzqy.sid),nsoednk.hasOwnProperty("pageModeConfig")&&
nsoednk.pageModeConfig.hasOwnProperty("wt")&&(b.wt=nsoednk.pageModeConfig.wt)}nds.config.placement?(b.wp=nds.config.placement,b.wpp=nds.config.placementPage):b.href=window.location.href;nds.ndeb&&(b.eb=nds.ndeb);nswaqs(a,b);"undefined"===typeof window.ndovStandaloneWidget||"c"!==a&&"pmd"!==a||(b.gf=HashUtil.ndovGrabFields(nsktzqytgf));return b}nds.getInputList=function(){return nsktzqy};
function nscsbbopd(a){return null!==a&&("object"===typeof a||"function"===typeof a)&&"number"===typeof a.length&&"undefined"!==typeof a.item}nds.sendOnEvent=function(a,b){a=document.getElementById(a);nds.common.addEventListener(a,b,nds.send)};nds.sendOnSubmit=function(){for(var a=document.getElementsByTagName("form"),b=0;b<a.length;++b)nds.common.addEventListener(a[b],"submit",nds.send)};function nsihscpgi(){return parseInt((new Date).getTime()/1E3,10)}
nds.registerListeners=function(a){function b(c,e){!1===nsxss.hasOwnProperty(c)?console.warn("Invalid event category used: '"+c+"'. Will be ignored."):(null!==e&&(!(e=parseInt(e))||0>=e)&&(console.warn("Invalid sampling rate used for event category: '"+c+"'. Default will be used."),e=null),!0===nscchy.hasOwnProperty(c)&&console.warn("Duplicate event category encountered: '"+c+"'."),nscchy[c]=e)}nscchy={};nsqsjnis=null;!0===nsulvzxx(a)?nsuhbmkiec(a,function(c,e){!0===nswaqszdct(c)?nsuhbmkiec(c,function(f,
q){b(q,f)}):b(c,null)}):null!==a&&void 0!==a&&console.warn("Invalid event category argument used. No categories will be enabled.");0===Object.keys(nscchy).length&&(nscchy[NDS_LISTEN_NONE]=null)};nds.resetListeners=function(){nscchy={};nsqsjnis=nscchy[NDS_LISTEN_ALL]=null};function nsulvzxxnc(a){return a.replace(/[A-Za-z]/g,function(b){return String.fromCharCode(b.charCodeAt(0)+("M">=b.toUpperCase()?13:-13))})}nds.getListeners=function(){null===nscchy&&nds.resetListeners();return nscchy};
nds.rebindListeners=function(){nstybxexx("rebind")};function nsihsc(a){return!0===nsoednk.useNdx?nsfvxu(a):nsulvzxxnc(a)}
function nsfvx(a){var b=Array(8),c=0>a?1:0,e=function(q,u){b[u]=q>>>24;b[u+1]=q>>>16&255;b[u+2]=q>>>8&255;b[u+3]=q&255};a=Math.abs(a);if(0===a)e(0,4),e(0<1/a?0:2147483648,0);else if(isNaN(a))e(0,4),e(2146959360,0);else if(1.7976931348623157E308<a)e(0,4),e((c<<31|2146435072)>>>0,0);else if(2.2250738585072014E-308>a)a/=4.9E-324,e(a>>>0,4),e((c<<31|a/4294967296)>>>0,0);else{var f=Math.floor(Math.log(a)/Math.LN2);1024===f&&(f=1023);a*=Math.pow(2,-f);e(4503599627370496*a>>>0,4);e((c<<31|f+1023<<20|1048576*
a&1048575)>>>0,0)}c=!1;e="";for(f=0;8>f;f++)if(a=b[f],0==a&&c||0!=a)a=a.toString(16),c&&2>a.length&&(a="0"+a),c=!0,e+=a;c||(e="0");return e}HashUtil.ndovGrabFields=function(a){return"ndovGrabFields not initialized in default mode"};nds.setInitTargets=function(a){nsnevfos=a};nds.addInitCallback=function(a){!1===nsulvzxx(nds.config.initCallbackList)&&(nds.config.initCallbackList=[]);"function"===typeof a&&-1===nds.config.initCallbackList.indexOf(a)&&nds.config.initCallbackList.push(a)};
function ndwts(a){nsyajts=a.ml;nsoednk=a.co;nsqsjnisez=a.wmd;nsktzqy=a.fd;nsnev=!0;nsoed=a.wc;nsoednk.initId&&(nsxssw=nsoednk.initId);nsfvxuey();nstybxexx("init");"undefined"!=typeof nsoednk.initBindings&&nds.setInitTargets(nsoednk.initBindings);"undefined"!==typeof nsoednk.apiBaseUrl&&nsoednk.apiBaseUrl&&nds.setApiBaseUrl(nsoednk.apiBaseUrl);nsuhb();nswaqszdc([])}function nsulvz(a,b,c,e){return{a:1,b:2,c:3,d:4}}
function nsuhbmkiec(a,b){var c;if(nsulvzxx(a)||nscsbbopd(a))for(c=0;c<a.length;c+=1)b(a[c],c,a);else if(nswaqszdct(a)){for(f in a)Object.prototype.hasOwnProperty.call(a,f)&&b(a[f],f,a);var e=nsuhbmkiec.ie8extraEnums;for(c=0;c<e.length;c+=1){var f=e[c];Object.prototype.hasOwnProperty.call(a,f)&&b(a[f],f,a)}}}nds.removeAllInitCallbacks=function(){nds.config.initCallbackList=[]};nds.setSessionId=function(a){nds.config.sessionId=a};nds.setSessionIdFromCookie=function(a){try{nds.setSessionId(nsfvxue(a))}catch(b){nds.setSessionId(null)}};
nds.setSessionIdFromSessionStorage=function(a){try{nds.setSessionId(window.sessionStorage.getItem(a))}catch(b){nds.setSessionId(null)}};nds.setSessionIdFromURL=function(a){"undefined"!==typeof nds.config.queryParams&&a in nds.config.queryParams?(a=nds.config.queryParams[a],nds.setSessionId(a?a:null)):nds.setSessionId(null)};function nsjmlp(a){for(var b=0;b<a.length;++b){var c=a[b];"function"===typeof c&&c()}}nds.setSessionIdFromDOM=function(a){try{nds.setSessionId(document.getElementById(a).value)}catch(b){nds.setSessionId(null)}};
nds.setSessionIdFromJS=function(a){if(a in window){var b=a=window[a];"function"===typeof a&&(b=a());nds.setSessionId(b?b:null)}else nds.setSessionId(null)};nds.setForceIP=function(a){nds.config.forceIP=a};function nscsb(a,b){try{window.sessionStorage.setItem(a,b)}catch(c){}}
function nsihscpgih(a){var b=[];nsoednk.hasOwnProperty("pageModeConfig")&&0<nsoednk.pageModeConfig.formbind.length&&(b=Array.prototype.concat.call(b,nsjmlpp(nsoednk.pageModeConfig.formbind)));a&&a.hasOwnProperty("formbind")&&a.formbind&&(b=Array.prototype.concat.call(b,nsjmlpp(a.formbind)));return b}nds.setPlacement=function(a){nds.config.placement=a};function attachEventListener(a,b,c,e){a=nds.common.addEventListener(a,b,c,getEnabledEvents());null!==a&&e(a)}
nds.setPlacementPage=function(a){nds.config.placementPage=a};nds.setTimeout=function(a){isNaN(a)?nds.config.sendTimeout=null:nds.config.sendTimeout=+a};
function nswaqszdc(a){if(nsoednk.hasOwnProperty("pageModeConfig")&&!0===nsoednk.pageModeConfig.enable){var b=nsoednk.pageModeConfig,c={};b.hasOwnProperty("options")&&(c=b.options,null!==a&&nsulvzxx(a)&&0<a.length&&(c&&!1===c.hasOwnProperty("formbind")&&(c.formbind=[]),c.formbind=Array.prototype.concat.call(c.formbind,a)));a=nswaq("pmd");a=nsoednkck(a);nsmnuq(a,c)}}nds.setForceUA=function(a){nds.config.forceUA=a};nds.setCspNonceForInit=function(a){nds.config.cspNonce=a};
nds.doNotTrack=function(){nds.config.doNotTrack=!0};nds.bindNewFields=function(a){nstybxexx("bind",a);nswaqszdc([])};nds.setPageModeFields=function(a){if(null!==a&&nsulvzxx(a)&&0<a.length){for(var b=0;b<nsoedn.length;b++)nsoedn[b].parentNode.removeChild(nsoedn[b]);nsoedn=[];nswaqszdc(a)}};nds.clear=function(){nstybxexx("clear")};function nstybxexx(a,b){for(var c in nsoednkc)if(nsoednkc.hasOwnProperty(c)){var e=nsoednkc[c];if(e.hasOwnProperty(a))(0,e[a])(nsqsjnisez[c],b)}}
nds.stop=function(){nstybxexx("stop");nsyajt.callAllCallbacks()};nds.ndwtr=function(){nstybxexx("reinit")};nds.setFormFieldData=function(a,b){nsktzqy[a]=b};nds.setApiBaseUrl=function(a){nsqsjn=a};nds.getApiBaseUrl=function(){return nsqsjn};"undefined"==typeof nds&&(nds=window.ndsapi||(window.ndsapi={}));nds.common={};function validateSessionIdCookie(a){if("string"!==typeof a)return!1;for(var b=["\x3d",":","\r","\n"],c=0;c<b.length;c++)if(-1!==a.indexOf(b[c]))return!1;return!0}nds.common.util={};
nds.common.bi={};nds.common.querySelectorAll=function(a){return document.querySelectorAll(a)};document.querySelectorAll||(nds.common.querySelectorAll=function(a){return[]});nds.common.addEventListener=function(a,b,c,e){if("object"===typeof e&&!1===e.hasOwnProperty(b))return null;try{a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}catch(f){}return function(){nds.common.removeEventListener(a,b,c)}};
function nsjmlpp(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var e=a[c];if("string"===typeof e&&document.getElementById(e))b.push(document.getElementById(e));else if(e.hasOwnProperty("type")&&e.hasOwnProperty("value"))switch(e.type){case "selector":var f=[];try{f=nds.common.querySelectorAll(e.value)}catch(q){}if(0<f.length)for(e.hasOwnProperty("index")&&(f=[f[e.index]]),e=0;e<f.length;e+=1)f[e]&&b.push(f[e])}}return b}
function nstybxe(a){nsktzqy.sid=a;if(!0===nsoednk.ndsidConfig.enable&&null!=a){var b=nsoednk.ndsidConfig.options.hasOwnProperty("formbind")&&nsoednk.ndsidConfig.options.formbind?nsjmlpp(nsoednk.ndsidConfig.options.formbind):document.getElementsByTagName("form");nswaqszd(b,nsyajtsqe,a)}}nds.common.removeEventListener=function(a,b,c){try{a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}catch(e){}};
function nsulvzx(a){var b=nsnevfosj();if(!1===validateSessionIdCookie(b))return null;if("undefined"!==typeof window.ndovStandaloneWidget||!0===nsoednk.clientSideCookie){var c="object"===typeof nsoednk.ndsidConfig&&"boolean"===typeof nsoednk.ndsidConfig.secure?nsoednk.ndsidConfig.secure:!1;if(null===nsfvxue(a)){var e=a+"\x3d"+b+";max-age\x3d"+nscchylsez+"; domain\x3d ."+nsmnuqj()+" ; path\x3d/";!0===c&&(e+="; secure; SameSite\x3dNone");document.cookie=e}null===nsfvxue(a)&&nscsb(a,b)}return b}
nds.common.createCallbackList=function(){var a=[];return{addCallback:function(b){b&&a.push(b)},callAllCallbacks:function(){for(var b=0;b<a.length;b+=1)(0,a[b])();a=[]}}};nds.common.util.truncTo=function(a,b,c){c="undefined"!==typeof c?c:"TRUNC";if("string"!==typeof a)return a;var e=b-c.length;return 1>e?a.substring(0,b):a.length>e?a.substring(0,e)+c:a};
nds.common.util.quickHash=function(a){var b=0,c=0,e;if(0===a.length)return"00000000";var f=0;for(e=a.length;f<e;f++){var q=a.charCodeAt(f);0===f%2?(b=(b<<5)-b+q,b|=0):(c=(c<<5)-c+q,c|=0)}0>b&&(b=4294967295+b+1);0>c&&(c=4294967295+c+1);return b.toString(16)+c.toString(16)};nds.common.bi.getScreenFingerprint=function(){var a="";window.screen&&(a+=[window.screen.width,window.screen.height].sort().join("x"),a+=" "+window.screen.colorDepth);return a};
nds.common.util.getComputedStyle=function(a,b){if(document.defaultView&&document.defaultView.getComputedStyle)return document.defaultView.getComputedStyle(a,null).getPropertyValue(b);try{if(a.currentStyle)return b=b.replace(/-(\w)/g,function(c,e){return e.toUpperCase()}),a.currentStyle[b]}catch(c){}};
nds.common.bi.getScreenInfo=function(){var a="";"undefined"!==typeof window.screen&&("undefined"!==typeof window.screen.width&&"undefined"!==typeof window.screen.height&&(a+=window.screen.width+"x"+window.screen.height),"undefined"!==typeof window.screen.availWidth&&"undefined"!==typeof window.screen.availHeight&&(a+=" "+window.screen.availWidth+"x"+window.screen.availHeight),"undefined"!==typeof window.screen.colorDepth&&(a+=" "+window.screen.colorDepth),"undefined"!==typeof window.screen.pixelDepth&&
(a+=" "+window.screen.pixelDepth));return a};nds.common.bi.isFlashInstalled=function(){try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),!0}catch(a){}try{if(void 0!=navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)return!0}catch(a){}return!1};nds.common.bi.getDeviceLanguage=function(){return window.navigator.userLanguage||window.navigator.language||window.navigator.browserLanguage};
nds.common.bi.getDeviceTimezone=function(){var a=(new Date(2014,0,2)).getTimezoneOffset(),b=(new Date(2014,5,2)).getTimezoneOffset();return Math.max(a,b)};function nsulvzxxn(){return window.innerWidth?window.innerHeight:document.documentElement&&document.documentElement.clientHeight?document.documentElement.clientHeight:document.body&&document.body.clientHeight?document.body.clientHeight:null}
nds.common.bi.getPlugins=function(){var a=[],b=/([0-9]+)\.[0-9|.]+/g;if(window.ActiveXObject){if(document.plugins&&0<document.plugins.length)for(var c=0;c<document.plugins.length;c++)a.push(document.plugins[c].src.replace(b,"$1"))}else try{if(navigator.plugins&&0<navigator.plugins.length)for(c=0;c<navigator.plugins.length;c++)a.push(navigator.plugins[c].name.replace(b,"$1"))}catch(e){a.push("denied")}0<a.length&&a.sort();b="p";for(c=0;c<a.length;c++)b+=","+a[c];return b};
nds.common.bi.getWebGLInfo=function(){for(var a={},b=document.createElement("canvas"),c=["webgl","experimental-webgl","moz-webgl","webkit-3d"],e,f=0;f<c.length;f++)try{if(e=b.getContext(c[f])){a.ContextName=c[f];break}}catch(q){}if(!(e&&"getParameter"in e))return null;b="VENDOR VERSION RENDERER SHADING_LANGUAGE_VERSION DEPTH_BITS MAX_VERTEX_ATTRIBS MAX_VERTEX_TEXTURE_IMAGE_UNITS MAX_VARYING_VECTORS MAX_VERTEX_UNIFORM_VECTORS MAX_COMBINED_TEXTURE_IMAGE_UNITS MAX_TEXTURE_SIZE MAX_CUBE_MAP_TEXTURE_SIZE NUM_COMPRESSED_TEXTURE_FORMATS MAX_RENDERBUFFER_SIZE MAX_VIEWPORT_DIMS ALIASED_LINE_WIDTH_RANGE ALIASED_POINT_SIZE_RANGE".split(" ");
for(c=0;c<b.length;c++)f=b[c],f in e&&(a[f]=e.getParameter(e[f]));return a};nds.common.bi.getDeviceTouchSettings=function(){var a={mtp:"NA"};"undefined"!==typeof navigator.maxTouchPoints?a.mtp=navigator.maxTouchPoints:"undefined"!==typeof navigator.msMaxTouchPoints&&(a.mtp=navigator.msMaxTouchPoints);a.ts=!1;"ontouchstart"in window&&(a.ts=!0);a.te=!1;try{document.createEvent("TouchEvent"),a.te=!0}catch(b){}return a};
function nswaqszd(a,b,c){var e=nsjmlpp([{type:"selector",value:'input[name\x3d"'+b+'"]'}]);if(0<e.length)for(a=0;a<e.length;a++)e[a].value=c;else if(0<a.length)for(var f=0;f<a.length;++f)e=a[f].querySelector("input[name\x3d"+b+"]"),null===e&&(e=document.createElement("input"),e.setAttribute("name",b),e.setAttribute("type","hidden"),a[f].appendChild(e)),e.setAttribute("value",c)}
nds.common.bi.getCookiesEnabled=function(a){var b=!0,c="undefined"!==typeof navigator.cookieEnabled&&navigator.cookieEnabled?!0:!1;if(1==a)try{document.cookie="ncookietest\x3d1; SameSite\x3dNone; Secure",b=-1!=document.cookie.indexOf("ncookietest\x3d"),document.cookie="ncookietest\x3d1; expires\x3dThu, 01-Jan-1970 00:00:01 GMT; SameSite\x3dNone; Secure"}catch(e){}return{tc:b,nc:c}};
nds.common.bi.getHTML5CanvasSignature=function(){var a="NA";try{var b=document.createElement("canvas");b.width=200;b.height=40;b.style.display="inline";var c=b.getContext("2d");c.fillText("aBc#$efG~ \ude73\ud63d",4,10);c.fillStyle="rgba(67, 92, 0, 0.5)";c.font="18pt Arial";c.fillText("aBc#$~efG \ude73\ud63d",8,12);a=b.toDataURL()}catch(e){}return a};
nds.common.bi.getFontMetrics=function(){var a=[];try{for(var b=document.createElement("canvas").getContext("2d"),c=nds.common.bi.fontMetricsFontList,e=0;e<c.length;e+=1){b.font='72px "'+c[e]+'"';var f=b.measureText("mmmmmmmmmmlli").width;a.push(f)}}catch(q){}return a};nds.common.bi.getHTML5LocalStorage=function(){var a=!1;try{var b=window.localStorage;b.setItem("ndls","ndls");b.removeItem("ndls");a=!0}catch(c){}return a};
nds.common.bi.getHTML5SupportedVideo=function(){var a="fv";try{var b=document.createElement("video"),c=["ogg","mp4","webm"];if("undefined"!==typeof b)for(var e in c)c.hasOwnProperty(e)&&""!=b.canPlayType("video/"+c[e])&&(a+=","+c[e])}catch(f){}return a};nds.common.bi.getHTML5SupportedAudio=function(){var a="fa";try{var b=document.createElement("audio"),c=["mpeg","ogg","wav"];if("undefined"!==typeof b)for(var e in c)c.hasOwnProperty(e)&&""!=b.canPlayType("audio/"+c[e])&&(a+=","+c[e])}catch(f){}return a};
nds.common.bi.getPlatform=function(){var a="NA";try{a=navigator.platform}catch(b){}return a};nds.common.bi.getVendor=function(){var a="NA";try{a=navigator.vendor}catch(b){}return a};nds.common.bi.fontMetricsFontList="monospace;sans-serif;serif;Andale Mono;Arial;Arial Black;Arial Hebrew;Arial MT;Arial Narrow;Arial Rounded MT Bold;Arial Unicode MS;Bitstream Vera Sans Mono;Book Antiqua;Bookman Old Style;Calibri;Cambria;Cambria Math;Century;Century Gothic;Century Schoolbook;Comic Sans;Comic Sans MS;Consolas;Courier;Courier New;Garamond;Geneva;Georgia;Helvetica;Helvetica Neue;Impact;Lucida Bright;Lucida Calligraphy;Lucida Console;Lucida Fax;LUCIDA GRANDE;Lucida Handwriting;Lucida Sans;Lucida Sans Typewriter;Lucida Sans Unicode;Microsoft Sans Serif;Monaco;Monotype Corsiva;MS Gothic;MS Outlook;MS PGothic;MS Reference Sans Serif;MS Sans Serif;MS Serif;MYRIAD;MYRIAD PRO;Palatino;Palatino Linotype;Segoe Print;Segoe Script;Segoe UI;Segoe UI Light;Segoe UI Semibold;Segoe UI Symbol;Tahoma;Times;Times New Roman;Times New Roman PS;Trebuchet MS;Verdana;Wingdings;Wingdings 2;Wingdings 3".split(";");
var nsqsjni;nsqsjni||(nsqsjni={});function nsuhbmki(a){var b=0;if(a instanceof Array)b=a.length;else for(var c in a)a.hasOwnProperty(c)&&b++;return b}Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){var c=this.length>>>0;b=Number(b)||0;b=0>b?Math.ceil(b):Math.floor(b);for(0>b&&(b+=c);b<c;b++)if(b in this&&this[b]===a)return b;return-1});var nscchyls="ic",NDS_LISTEN_FOCUS="fc",NDS_LISTEN_TOUCH="to",NDS_LISTEN_KEYBOARD="kb";
function ndwti(a){nsktzq=nsihscpgi();nsnevfo=nsihscpgi();nsktzqy.wt=a.fd.wt;nsoednk.hasOwnProperty("pageModeConfig")&&nsoednk.pageModeConfig.hasOwnProperty("wt")&&0===nsoednk.pageModeConfig.wt.length&&nsoednk.pageModeConfig.hasOwnProperty("requireWidgetToken")&&!0===nsoednk.pageModeConfig.requireWidgetToken&&(nsoednk.pageModeConfig.wt=nsktzqy.wt,nswaqszdc([]));nsktzqytgf=a.gf;if(null!=a.wab){var b=a.wab;b=nsjmlpp(b);for(var c in b){var e=b[c];if(null!=e){var f="FORM"===e.tagName?"submit":"click";
nds.common.addEventListener(e,f,nds.send)}}}if(null!=a.ls&&(f=a.ls,e=ndoGetObjectKeys(f),b=nsuhbmki(f),0<b))for(c=0;c<b;c++)window.localStorage.setItem(e[c],f[e[c]]);if(null!=a.cwd){if("undefined"==typeof document.addEventListener)return null;a.cwd.websiteId=a.wi;var q=a.cwd;null!=q.pr&&null==q.cp&&nds.config.placement&&nds.config.placementPage&&(a=nds.config.placement+"."+nds.config.placementPage,c=q.pr,c[a]&&(q.cp=c[a],q.cp.placement=nds.config.placement,q.cp.page=nds.config.placementPage));if(null!=
q.cp)if(null!=q.cp.bindmethod&&"manual"==q.cp.bindmethod)nds.callApi=function(C){nsxsswrsy(q,C)},nds.completeAndCallApi=function(C){nds.send(function(){nds.callApi(C)})};else for(b=null==q.cp.autobind?document.getElementsByTagName("form"):nsjmlpp(q.cp.autobind),c=0;c<b.length;c++)if(e=b[c],null!=e){var u=(a="function"===typeof e.onsubmit)?e.onsubmit:function(){return!0};f="FORM"===e.tagName?"submit":"click";(function(C,z,l,g){var h=function(m){var v=m||window.event;v.preventDefault?v.preventDefault():
v.returnValue=!1;nsxsswrsy(q,function(y,n){if(1==l){C.onsubmit=function(){};try{z(v)}catch(r){}}else nds.common.removeEventListener(C,g,h);if(C.submit)try{C.submit()}catch(r){C.constructor.prototype.submit.call(C)}else C.click()})};!0===l?C.onsubmit=h(g):nds.common.addEventListener(C,g,h)})(e,u,a,f)}}!0===nsoednk.ndsidConfig.enable&&(a=nsfvxue(nsyajtsqe),null!==a&&(nds.setSessionIdFromCookie(nsyajtsqe),nscsb(nsyajtsqe,a)),nstybxe(nsjmlpptsb(nsyajtsqe)))}
function nswaqs(a,b){if(nsyajts.hasOwnProperty(a))for(var c in nsyajts[a])nsyajts[a].hasOwnProperty(c)&&nsktzqy.hasOwnProperty(c)&&nsktzqy[c]&&(b[c]=nsktzqy[c])}var NDS_LISTEN_DEVICE_MOTION_SENSORS="dm";function nsuhbm(){null==nds.config.sessionId&&nds.setSessionIdFromCookie(nsyajtsqe);null==nds.config.sessionId&&nds.setSessionIdFromSessionStorage(nsyajtsqe);null==nds.config.sessionId&&null!==nsxsswr&&(nds.setSessionId(nsxsswr),nscsb(nsyajtsqe,nsxsswr))}
var NDS_LISTEN_MOUSE="mo",NDS_LISTEN_FORM="fr",NDS_LISTEN_PASTE="pe",NDS_LISTEN_ALL="de";function HashUtil(){}var NDS_LISTEN_NONE="no",nsxsswrsym="focus";function nsuhbmkie(a){nsoedn=nsjmlpp([{type:"selector",value:'input[name\x3d"'+nsnevf+'"]'}])}var nsmnu="blur",nsktzqytg="touchstart",nscchyl="keydown";function nsfvxueym(a,b){if("string"===typeof b){var c=b;b=function(f){return f[c]}}var e=nsulvzxx(a)?[]:nswaqszdct(a)?{}:void 0;nsuhbmkiec(a,function(f,q){e[q]=b(f,q,a)});return e}
var nsktz="keyup",nsnevfosjd="devicemotion",nsoednkcky="deviceorientation",nscchylse="mousemove",nsmnuqjc="click",nscch="submit",nsktzqyt="change",nsyaj="input";function nsuhb(){if(nsoednk.hasOwnProperty("pageModeConfig")&&!0===nsoednk.pageModeConfig.enable){var a=nsoednk.pageModeConfig;a.hasOwnProperty("inputFieldName")&&0<a.inputFieldName.length&&(nsnevf=a.inputFieldName);!0===nsoednk.ndsidConfig.enable&&nsuhbm();!1===nsyajts.hasOwnProperty("pmd")&&(nsyajts.pmd={pmdModuleMissing:!0})}}
function nsjmlppts(a){a=nswaq(a);var b=[],c=0,e={r:a.r,sid:a.sid,wt:a.wt},f;for(f in a)if(a.hasOwnProperty(f))if(a[f]){var q=a[f],u=f.length+q.toString().length;2E3<u?(u={r:a.r,sid:a.sid,wt:a.wt},u[f]=q,b.push(nsqsjni.stringify(u))):2E3<u+c?(b.push(nsqsjni.stringify(e)),e={r:a.r,sid:a.sid,wt:a.wt},e[f]=q,c=u):(e[f]=q,c+=u)}else delete a[f];0<c&&b.push(nsqsjni.stringify(e));return b}var nsqsj="paste",nsxss={};nsxss[NDS_LISTEN_FOCUS]=[nsxsswrsym,nsmnu];nsxss[NDS_LISTEN_TOUCH]=[nsktzqytg];
nsxss[NDS_LISTEN_KEYBOARD]=[nscchyl,nsktz];function nstybxex(a,b,c){nsuhbmkiec(a,function(e,f){c=b(c,e,f,a)});return c}function nswaqszdct(a){return"object"===typeof a&&null!==a&&!nsulvzxx(a)}nsxss[NDS_LISTEN_DEVICE_MOTION_SENSORS]=[nsnevfosjd,nsoednkcky];function nsjmlpptsb(a){if(null==nds.config.sessionId){var b=nsfvxue(a);if(null==b){try{b=window.sessionStorage.getItem(a)}catch(c){b=null}null==b&&(b=nsulvzx(a))}return b}return nds.config.sessionId}nsxss[NDS_LISTEN_MOUSE]=[nscchylse,nsmnuqjc];
nsxss[NDS_LISTEN_FORM]=[nscch,nsktzqyt,nsyaj];function nsuhbmk(){return 8.742834613345816E-5}nsxss[NDS_LISTEN_PASTE]=[nsqsj];var ndoIsKeyIncluded=function(a,b,c){return-1!==b.indexOf(a.key)||-1!==c.indexOf(a.keyCode)?!0:!1},ndoIsModifierKey=function(a){return ndoIsKeyIncluded(a,["Shift","Control","Meta","Alt","CapsLock"],[16,17,91,93,18,20])};function nsihscpg(){return nsihs()+":"+nsulvzxxn()+":"+window.outerWidth+":"+window.outerHeight+":"+screen.availWidth+":"+screen.availHeight}
var ndoIsNavigationKey=function(a){return ndoIsKeyIncluded(a,"Tab PageUp PageDown End Home ArrowLeft Left ArrowUp Up ArrowRight Right ArrowDown Down".split(" "),[9,33,34,35,36,37,38,39,40])},ndoIsEditingKey=function(a){return ndoIsKeyIncluded(a,["Insert","Delete","Backspace","Del"],[45,46,8])},KEYBOARD_LOCATION={STANDARD:0,LEFT:1,RIGHT:2,NUMPAD:3},KEY_TYPE_AND_LOCATION={NORMAL_STANDARD:0,MODIFIER_STANDARD:4,NAVIGATION_STANDARD:8,EDITING_STANDARD:12};
function nsfvxue(a,b){return(b=document.cookie.match("(^|;)\\s*"+a+"\\s*\x3d\\s*([^;]+)"))?b.pop():null}
var ndoGetKeyboardLocation=function(a){a=a.location;var b=Object.keys(KEYBOARD_LOCATION).map(function(c){return KEYBOARD_LOCATION[c]});return"undefined"===typeof a||-1===b.indexOf(a)?KEYBOARD_LOCATION.STANDARD:a},ndoGetKeyTypeAndLocationIndicator=function(a){var b=ndoGetKeyboardLocation(a);return!0===ndoIsModifierKey(a)?KEY_TYPE_AND_LOCATION.MODIFIER_STANDARD+b:!0===ndoIsNavigationKey(a)?KEY_TYPE_AND_LOCATION.NAVIGATION_STANDARD+b:!0===ndoIsEditingKey(a)?KEY_TYPE_AND_LOCATION.EDITING_STANDARD+b:KEY_TYPE_AND_LOCATION.NORMAL_STANDARD+
b};nsuhbmkiec.ie8extraEnums=function(){return{toString:null}.propertyIsEnumerable("toString")?[]:"toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" ")}();
var ndoGetObjectKeys=function(){var a=Object.prototype.hasOwnProperty,b=!{toString:null}.propertyIsEnumerable("toString"),c="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),e=c.length;return function(f){if("object"!==typeof f&&("function"!==typeof f||null===f))throw new TypeError("ndoGetObjectKeys called on non-object");var q=[],u;for(u in f)a.call(f,u)&&q.push(u);if(b)for(u=0;u<e;u++)a.call(f,c[u])&&q.push(c[u]);return q}}();
function nsfvxuey(){nds.config.hasOwnProperty("beforeInitQ")&&nsjmlp(nds.config.beforeInitQ)}var nsxsswrs=!1;document.querySelector||(nsxsswrs=!0);(function(){nsihscp("wk",{init:function(a){nsnev&&(a=Math.floor(1E6*Math.random())+1E3,(window.ndsapi||(window.ndsapi={})).setFormFieldData("wkr",a))}})})();
(function(){nsihscp("di",{init:function(a){nds=window.ndsapi||(window.ndsapi={});if(nds.config.doNotTrack)nds.setFormFieldData("dnt",!0);else{var b={},c="NotAvail";"undefined"!==typeof navigator&&"undefined"!==typeof navigator.userAgent&&(c=navigator.userAgent);var e=window.ndsapi||(window.ndsapi={});e.config&&e.config.forceUA&&(c=e.config.forceUA);c=c.replace(/([0-9]+\.[0-9]+)\.[0-9]+\.[0-9]+/g,"$1").replace(/([0-9]+\.[0-9]+)\.[0-9]+/g,"$1");c=c.replace(/([0-9]+_[0-9]+)_[0-9]+_[0-9]+/g,"$1").replace(/([0-9]+_[0-9]+)_[0-9]+/g,
"$1");b.ua=c;b.sr=nds.common.bi.getScreenFingerprint();b.didtz=nds.common.bi.getDeviceTimezone().toString();c=nds.common.bi.getPlugins();b.bp=nds.common.util.quickHash(c);b.rbp=c;b.flv=nds.common.bi.isFlashInstalled().toString();b.fv=nds.common.bi.getHTML5SupportedVideo();b.fa=nds.common.bi.getHTML5SupportedAudio();b.hf=nds.common.util.quickHash(nds.common.bi.getHTML5CanvasSignature());b.pl=nds.common.bi.getPlatform();b.ve=nds.common.bi.getVendor();b.ft=nsqsjni.stringify(nds.common.bi.getDeviceTouchSettings());
b.fc=nsqsjni.stringify(nds.common.bi.getCookiesEnabled(a.ac));b.fs=nds.common.bi.getHTML5LocalStorage().toString();b.wg=nds.common.util.quickHash(nsqsjni.stringify(nds.common.bi.getWebGLInfo()));b.fm=nds.common.util.quickHash(nds.common.bi.getFontMetrics().join(","));for(var f in b)b.hasOwnProperty(f)&&nds.setFormFieldData(f,b[f])}b=nds;f=b.setFormFieldData;c=[];c.push(nds.common.bi.getScreenInfo());c.push(nds.common.bi.getDeviceTimezone());c.push(nds.common.bi.getDeviceLanguage());c.push("bp1-"+
nds.common.util.quickHash(nds.common.bi.getPlugins()));c.push(nds.common.bi.isFlashInstalled().toString());e=a.rt||128;c.push(nds.common.util.truncTo(document.referrer.replace(/\|/g,""),e));a=a.ut||512;c.push(nds.common.util.truncTo(navigator.userAgent.replace(/\|/g,""),a));a=nds.common.bi.getWebGLInfo();null===a?c.push("Not Supported"):c.push("wg1-"+nds.common.util.quickHash(nsqsjni.stringify(a)));a="b2";for(e=0;e<c.length;e++)a+="|"+c[e];f.call(b,"bi",a)}})})();
(function(){function a(z){return 10>z?"0"+z:z}function b(z,l){var g=f,h=l[z];h&&"object"===typeof h&&"function"===typeof h.toNDJSON&&(h=h.toNDJSON(z));"function"===typeof C&&(h=C.call(l,z,h));switch(typeof h){case "string":return c(h);case "number":return isFinite(h)?String(h):"null";case "boolean":case "null":return String(h);case "object":if(!h)return"null";f+=q;var m=[];if("[object Array]"===Object.prototype.toString.apply(h)){var v=h.length;for(z=0;z<v;z+=1)m[z]=b(z,h)||"null";l=0===m.length?
"[]":f?"[\n"+f+m.join(",\n"+f)+"\n"+g+"]":"["+m.join(",")+"]";f=g;return l}if(C&&"object"===typeof C)for(v=C.length,z=0;z<v;z+=1){if("string"===typeof C[z]){var y=C[z];(l=b(y,h))&&m.push(c(y)+(f?": ":":")+l)}}else for(y in h)Object.prototype.hasOwnProperty.call(h,y)&&(l=b(y,h))&&m.push(c(y)+(f?": ":":")+l);l=0===m.length?"{}":f?"{\n"+f+m.join(",\n"+f)+"\n"+g+"}":"{"+m.join(",")+"}";f=g;return l}}function c(z){e.lastIndex=0;return e.test(z)?'"'+z.replace(e,function(l){var g=u[l];return"string"===typeof g?
g:"\\u"+("0000"+l.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+z+'"'}"function"!==typeof Date.prototype.toNDJSON&&(Date.prototype.toNDJSON=function(z){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toNDJSON=Number.prototype.toNDJSON=Boolean.prototype.toNDJSON=function(z){return this.valueOf()});var e=/[\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
f,q,u={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},C;"function"!==typeof nsqsjni.stringify&&(nsqsjni.stringify=function(z,l,g){var h;q=f="";if("number"===typeof g)for(h=0;h<g;h+=1)q+=" ";else"string"===typeof g&&(q=g);if((C=l)&&"function"!==typeof l&&("object"!==typeof l||"number"!==typeof l.length))throw Error("nsqsjni.stringify");return b("",{"":z})});"function"!==typeof nsqsjni.parse&&(nsqsjni.parse=function(){var z,l,g={'"':'"',"\\":"\\","/":"/",b:"\b",f:"\f",
n:"\n",r:"\r",t:"\t"},h,m=function(B){if(B&&B!==l)throw new SyntaxError('nsqsjni.parse - Expected "'+B+'" instead of "'+l+'"');l=h.charAt(z);z+=1;return l},v=function(){var B="";"-"===l&&(B="-",m("-"));for(;"0"<=l&&"9">=l;)B+=l,m();if("."===l)for(B+=".";m()&&"0"<=l&&"9">=l;)B+=l;if("e"===l||"E"===l){B+=l;m();if("-"===l||"+"===l)B+=l,m();for(;"0"<=l&&"9">=l;)B+=l,m()}var p=+B;return isFinite(p)?p:"-"===B.charAt(0)?-Infinity:Infinity},y=function(){var B,p="",A;if('"'===l)for(;m();){if('"'===l)return m(),
p;if("\\"===l)if(m(),"u"===l){for(B=A=0;4>B;B+=1){var E=parseInt(m(),16);if(!isFinite(E))break;A=16*A+E}p+=String.fromCharCode(A)}else if("string"===typeof g[l])p+=g[l];else break;else p+=l}throw new SyntaxError("nsqsjni.parse - Bad string");},n=function(){for(;l&&" ">=l;)m()},r=function(){switch(l){case "t":return m("t"),m("r"),m("u"),m("e"),!0;case "f":return m("f"),m("a"),m("l"),m("s"),m("e"),!1;case "n":return m("n"),m("u"),m("l"),m("l"),null}throw new SyntaxError('nsqsjni.parse - Unexpected "'+
l+'"');};var x=function(){n();switch(l){case "{":a:{var B={};if("{"===l){m("{");n();if("}"===l){m("}");var p=B;break a}for(;l;){p=y();n();m(":");B[p]=x();n();if("}"===l){m("}");p=B;break a}m(",");n()}}throw new SyntaxError("nsqsjni.parse - Bad object");}return p;case "[":a:{p=[];if("["===l){m("[");n();if("]"===l){m("]");break a}for(;l;){p.push(x());n();if("]"===l){m("]");break a}m(",");n()}}throw new SyntaxError("nsqsjni.parse - Bad array");}return p;case '"':return y();case "-":return v();default:return"0"<=
l&&"9">=l?v():r()}};return function(B,p){h=B;z=0;l=" ";B=x();n();if(l)throw new SyntaxError("nsqsjni.parse - Syntax error");return"function"===typeof p?function F(E,G){var H,L=E[G];if(L&&"object"===typeof L)for(H in L)if(Object.prototype.hasOwnProperty.call(L,H)){var ha=F(L,H);void 0!==ha?L[H]=ha:delete L[H]}return p.call(E,G,L)}({"":B},""):B}}())})();
(function(){function a(p){if(!0===(0!==p.coords.longitude&&0!==p.coords.latitude)){C=p;z=null;var A=C;p=[];p[x.LATITUDE]=A.coords.latitude;p[x.LONGITUDE]=A.coords.longitude;p[x.TIMESTAMP]=A.timestamp;null===A.coords.altitude||isNaN(A.coords.altitude)||(p[x.ALTITUDE]=A.coords.altitude);null===A.coords.accuracy||isNaN(A.coords.accuracy)||(p[x.HORIZONTAL_ACCURACY]=A.coords.accuracy);null===A.coords.altitudeAccuracy||isNaN(A.coords.altitudeAccuracy)||(p[x.VERTICAL_ACCURACY]=A.coords.altitudeAccuracy);
null===A.coords.heading||isNaN(A.coords.heading)||(p[x.BEARING]=A.coords.heading);null===A.coords.speed||isNaN(A.coords.speed)||(p[x.SPEED]=A.coords.speed);if(null===p||0===Object.keys(p).length)nsmnuqjcs="";else{var E=A="",G;for(G in p){var F=nsfvx(p[G]);A=A.concat(G);E=E.concat(".").concat(F)}nsmnuqjcs=A.concat(E)}}else l.push(B.LOCATION_API_FAILED),nsmnuqjcs=q();b(nsmnuqjcs)}function b(p){u.setFormFieldData("mloc",p);if(0<nsoedn.length&&nsoedn[0].value){var A=nsoedn[0].value,E=p="",G=nsoednk.hasOwnProperty("pageModeConfig")&&
!0===nsoednk.pageModeConfig.encodeData;G&&(A=nsihsc(A));try{for(E=nsqsjni.parse(A),E[nsyajtsqee]||(E[nsyajtsqee]={}),nsyajts.pmd.hasOwnProperty("mloc")&&nsktzqy.hasOwnProperty("mloc")&&(E[nsyajtsqee].mloc=nsktzqy.mloc),p=nsqsjni.stringify(E),G&&(p=nsihsc(p)),A=0;A<nsoedn.length;A++)nsoedn[A].value=p}catch(F){}}}function c(p){"undefined"!==typeof navigator&&"undefined"!==typeof navigator.geolocation?navigator.geolocation.getCurrentPosition(a,f,p):e()}function e(){l.push(B.DEVICE_LOCATION_DISABLED);
C=null;z="Geolocation is not supported by this browser";nsmnuqjcs=q();b(nsmnuqjcs)}function f(p){C=null;z=p.message;p.code===n?l.push(B.LOCATION_PERMISSIONS_NOT_GRANTED):p.code===r?l.push(B.LOCATION_API_NULL):l.push(B.LOCATION_API_FAILED);nsmnuqjcs=q();b(nsmnuqjcs)}function q(){var p="r",A=0,E;for(E in l)A|=1<<l[E];l=[];A=A.toString(16);p=p.concat(A);"undefined"!==typeof z&&null!==z&&(A=btoa(z),p=p.concat(".").concat(A));return p}var u=window.ndsapi||(window.ndsapi={}),C,z,l=[],g=!1,h=0,m=0,v={timeout:1800},
y={enableHighAccuracy:!0,timeout:4E3,maximumAge:0},n=1,r=2,x={ALTITUDE:"a",BEARING:"b",BEARING_ACCURACY:"c",SPEED_ACCURACY:"e",HORIZONTAL_ACCURACY:"h",LATITUDE:"i",LONGITUDE:"n",SPEED:"s",TIMESTAMP:"t",VERTICAL_ACCURACY:"v"},B={DEVICE_LOCATION_DISABLED:0,GOOGLE_PLAY_SERVICES_NOT_AVAILABLE:1,LOCATION_PERMISSIONS_NOT_IN_MANIFEST:2,LOCATION_PERMISSIONS_NOT_GRANTED:3,LOCATION_API_NULL:4,LOCATION_API_FAILED:5};nsihscp("dl",{init:function(p){!0===u.config.isLocationProcessingEnabled&&null!==nsmnuqjcs&&
b(nsmnuqjcs)},stop:function(p){u.config.isLocationProcessingEnabled=!1;u.disableLocationProcessing()}});u.enableLocationProcessing=function(p){u.config.isLocationProcessingEnabled=!0;!1===isNaN(p)&&"number"===typeof p&&+p===parseInt(p)?u.config.refreshInterval=Math.abs(p):u.config.refreshInterval=0;!1===g&&(g=u.config.isLocationProcessingEnabled,0<=u.config.refreshInterval&&(h=u.config.refreshInterval),c(v),0<h?(y.maximumAge=1E3*h,y.timeout=Infinity,"undefined"!==typeof navigator&&"undefined"!==typeof navigator.geolocation?
m=navigator.geolocation.watchPosition(a,f,y):e()):(y.maximumAge=Infinity,c(y)))};u.disableLocationProcessing=function(){u.config.isLocationProcessingEnabled=!1;u.config.refreshInterval=0;g=u.config.isLocationProcessingEnabled;0!==m&&(navigator.geolocation.clearWatch(m),m=0)}})();
(function(){var a=window.ndsapi||(window.ndsapi={}),b=null,c=null,e=null;a.configure3DS=function(n){a.config=a.config||{};a.config.threeDSConfig=a.config.threeDSConfig||{};a.ThreeDS={};nsuhbmkiec(n,function(r,x){!1===Object.prototype.hasOwnProperty.call(a.config.threeDSConfig,x)&&(a.config.threeDSConfig[x]={});a.config.threeDSConfig[x]=n[x]})};a.start3DS=function(n){if(f()){var r=a.config.threeDSConfig;q(r);var x=function(A,E,G){if("undefined"!==typeof ThreeDS.ThreeDS2Widget){var F=C(A,E);var H="transaction.error"}else"undefined"!==
typeof ThreeDS.ThreeDS1Widget&&(H=new ThreeDS.ErrorInformation,H.setCause(ThreeDS.ErrorCause.INVALID_REQUEST),H.setExplanation(A+": "+E),F=new ThreeDS.ThreeDSError,F.setError(H),F.setResult(ThreeDS.ErrorResult.ERROR),H=ThreeDS.Flow.THREE_DS1_TRANSACTION_ERROR);u(H,[F],G)};if("undefined"!==typeof ThreeDS)if(a.ThreeDS=ThreeDS,a.ThreeDS.Error=ThreeDS.ThreeDSError,0!==e.length)x("Missing Configuration",e.join(","),c.callbacks);else{var B=z(r),p=l(B);if(0!==p.length)x("Missing 3DS Widget",p.join(","),
c.callbacks);else if(x=m(B,c.notificationUrl))x.start({iframeElement:v(c.iframeElement),callbacks:c.callbacks,threeDSMethodNotificationURL:r.threeDSMethodNotificationURL,authPayload:r.authPayload,supportedVersionsResponse:n,enableIDCIMode:r.enableIDCIMode}),h(B)}}};a.get3dsAuthenticationParameters=function(n){if(f()){var r=a.config.threeDSConfig;q(r);if("undefined"!==typeof ThreeDS&&(a.ThreeDS=ThreeDS,a.ThreeDS.Error=ThreeDS.ThreeDSError,g()))return b=new ThreeDS.ThreeDS2Widget(c.notificationUrl),
b.getAuthenticationParameters(n,{iframeElement:v(c.iframeElement),callbacks:c.callbacks,threeDSMethodNotificationURL:r.threeDSMethodNotificationURL,authPayload:r.authPayload})}};a.perform3dsChallenge=function(n){if(f()){var r=a.config.threeDSConfig;q(r);if("undefined"!==typeof ThreeDS&&(a.ThreeDS=ThreeDS,a.ThreeDS.Error=ThreeDS.ThreeDSError,g()))return null===b&&(b=new ThreeDS.ThreeDS2Widget(c.notificationUrl)),b.performChallenge(n,{iframeElement:v(c.iframeElement),callbacks:c.callbacks,threeDSMethodNotificationURL:r.threeDSMethodNotificationURL,
authPayload:r.authPayload})}};var f=function(){return Object.prototype.hasOwnProperty.call(a,"config")&&Object.prototype.hasOwnProperty.call(a.config,"threeDSConfig")&&0<nsuhbmki(a.config.threeDSConfig)},q=function(n){c={iframeElement:null,callbacks:null,notificationUrl:null};e=[];nsuhbmkiec(c,function(r,x){Object.prototype.hasOwnProperty.call(n,x)?c[x]=n[x]:e.push(x)})},u=function(n,r,x){(n=y(x,n))&&n.apply(this,r)},C=function(n,r){var x=new ThreeDS.ThreeDSError;x.setErrorDescription(n);x.setErrorDetail(r);
x.setMessageType(ThreeDS.MsgType.ERRO);x.setErrorCode(ThreeDS.ErrorCode.PERMANENT_SYSTEM_FAILURE);x.setErrorComponent(ThreeDS.ErrorComponent.THREEDS_SDK);return x},z=function(n){var r="None";Object.prototype.hasOwnProperty.call(n,"interdictionType")&&(r=n.interdictionType);return r},l=function(n){var r=[];nsuhbmkiec({"3ds1":["ThreeDS1Widget"],"3ds2":["ThreeDS2Widget"],"3ds2First":["ThreeDS1Widget","ThreeDS2Widget"]}[n],function(x){"undefined"===typeof ThreeDS[x]&&r.push(x)});return r},g=function(){if(0!==
e.length){var n=e.join(","),r=c.callbacks;if("undefined"!==typeof ThreeDS.ThreeDS2Widget){var x=C("Missing Configuration",n);var B="transaction.error"}u(B,[x],r);return!1}return"undefined"===typeof ThreeDS.ThreeDS2Widget?!1:!0},h=function(n){nsuhbmkiec({"3ds1":["ThreeDSWidget","ThreeDS2Widget"],"3ds2":["ThreeDSWidget","ThreeDS1Widget"],"3ds2First":["ThreeDSWidget"]}[n],function(r){delete ThreeDS[r]})},m=function(n,r){return"3ds1"===n?new ThreeDS.ThreeDS1Widget(r):"3ds2"===n||"3ds2First"===n?new ThreeDS.ThreeDS2Widget(r):
"undefined"!==typeof ThreeDS?new ThreeDS.ThreeDSWidget(r):null},v=function(n){var r=n;if("string"===typeof n||n instanceof String)r=nsjmlpp([n]),r=0<r.length?r[0]:null;return r},y=function(n,r){if("object"!==typeof n)return!1;if("string"===typeof r){r=r.split(".");for(var x=r.length,B=0;B<x;B++){var p=r[B];if(Object.prototype.hasOwnProperty.call(n,p)){if(B===x-1)return"function"===typeof n[p]?n[p]:!1;n=n[p]}else return!1}}else return Object.prototype.hasOwnProperty.call(n,r)&&"function"===typeof n[r]?
n[r]:!1};"function"!==typeof a.load&&(a.load=function(){if(nsxsswrs)a.configure3DS=function(){},a.start3DS=function(){};else for(var n=a.config.q,r=0;r<n.length;++r){var x=n[r];"function"===typeof x&&x()}})})();
(function(){var a=!1,b='input[type\x3d"text"],input[type\x3d"password"]',c='input[name\x3d"remember-me"]',e=function(g){a&&f.init()};nsihscp("af",{init:function(g){a=g.e;b=g.gtfs;c=g.rms;a&&f.init()},precomplete:function(g){a&&f.findTech()},bind:e,rebind:e,stop:function(g){a&&(u.unsubscribeAll(),a=!1)}});var f=function(){return{init:function(){q.init();this.initFieldWatchers();this.findTech()},findTech:function(){try{z.findTech(),l.findTech(),C.findTech()}catch(g){}},initFieldWatchers:function(){u.unsubscribeAll();
for(var g=this.getTargetFields(),h=0;h<g.length;h+=1)u.startWatchingField(g[h])},getTargetFields:function(){return nds.common.querySelectorAll(b)}}}(),q=function(){function g(){var m=ndoGetObjectKeys(h).join(",");nds.setFormFieldData("af",m)}var h={};return{init:function(){h={};g()},reportTech:function(m){h[m]=!0;g()},reportFill:function(){h.filled=!0;g()}}}(),u=function(){function g(){var v=nds.common.createCallbackList(),y=++m;h[y]=v;v.addCallback(function(){delete h[y]});return v}var h={},m=0;
return{unsubscribeAll:function(){for(var v in h)Object.prototype.hasOwnProperty.call(h,v)&&h[v].callAllCallbacks()},startWatchingField:function(v){if(v)if(v.value)q.reportFill();else{var y=getEnabledEvents();if(!1!==y.hasOwnProperty(nsxsswrsym)&&!1!==y.hasOwnProperty(nsyaj)&&!1!==y.hasOwnProperty(nsktzqyt)){var n=g();attachEventListener(v,nsxsswrsym,function(){n.callAllCallbacks()},n.addCallback);y=[nsktzqyt,nsyaj];for(var r=0;r<y.length;r+=1)attachEventListener(v,y[r],function(){v.value&&(q.reportFill(),
n.callAllCallbacks())},n.addCallback)}}}}}(),C=function(){return{findTech:function(){try{for(var g=nds.common.querySelectorAll(c),h=0;h<g.length;h+=1)g[h].checked&&q.reportTech("rememberme")}catch(m){}}}}(),z=function(){return{findTech:function(){try{0<nds.common.querySelectorAll(":-webkit-autofill").length&&q.reportTech("webkit")}catch(g){}}}}(),l=function(){var g={"background-attachment":"scroll","background-size":"16px 18px","background-position":"98% 50%","background-repeat":"no-repeat","background-image":/^url\("data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAA..JREFUOB.*"\)$/};
return{findTech:function(h){h||(h=f.getTargetFields());for(var m=0;m<h.length;m+=1){var v=h[m];a:{var y=void 0;var n=v,r=g;for(y in r)if(Object.prototype.hasOwnProperty.call(r,y)){var x=r[y],B=nds.common.util.getComputedStyle(n,y);if(x instanceof RegExp){if(!x.test(B)){y=!1;break a}}else if(B!==x){y=!1;break a}}y=!0}if(!y){y=void 0;v=v.id||v.name;try{y=document.querySelector('[id^\x3d"__lpform_'+v+'"]')}catch(p){}y=!!y}if(y){q.reportTech("lastpass");break}}}}}()})();
(function(){function a(){Y=Z=M="";R=null;aa="";pa=x();qa&&(g(ra,[]),qa=!1)}function b(){var d=x();var k="";var t=nds.getListeners(),w;for(w in t)k+=w+(t[w]||"");t=Math.floor((d-pa)/1E3);aa=0<la&&aa.length>la?t.toString(16)+","+Ca+";0,"+k+";":aa+(t.toString(16)+","+k+";");pa=d;nds.setFormFieldData(nscchyls,aa);f(!1)}function c(d,k){var t=ba[d],w=Date.now();return w-t>k?(ba[d]=w,!0):!1}function e(d){var k=0,t=0;if(d.pageX||d.pageY)k=d.pageX,t=d.pageY;else if(d.clientX||d.clientY)k=d.clientX+document.body.scrollLeft+
document.documentElement.scrollLeft,t=d.clientY+document.body.scrollTop+document.documentElement.scrollTop;return{x:k,y:t}}function f(d){if(0<nsoedn.length&&nsoedn[0].value){var k=nsoedn[0].value,t="",w="",D="",I="";nsoednk.hasOwnProperty("pageModeConfig")&&!0===nsoednk.pageModeConfig.encodeData&&(k=nsihsc(k));try{w=nsqsjni.parse(k);w[nsyajtsqee]||(w[nsyajtsqee]={});var sa=0<Y.length?Y:Z.toString(),Da=w[nsyajtsqee].hasOwnProperty("ipr")?w[nsyajtsqee].ipr:"";k=aa;!0===d&&(sa.length!==Da.length&&(sa=
Da),w[nsyajtsqee].hasOwnProperty(nscchyls)&&k.length!==w[nsyajtsqee][nscchyls].length&&(k=w[nsyajtsqee][nscchyls]));var ta={ipr:sa,forceIP:nds.config.forceIP,wp:nds.config.placement,wpp:nds.config.placementPage,dtrk:nds.config.doNotTrack};ta[nscchyls]=k;"sid"in nsyajts.pmd&&null!=nds.config.sessionId&&0<nds.config.sessionId.length&&(w.sid=nds.config.sessionId);for(var Ea in nsyajts.pmd)nsyajts.pmd.hasOwnProperty(Ea)&&(D=Ea,I=w[nsyajtsqee].hasOwnProperty(D)?w[nsyajtsqee][D]:"",ta.hasOwnProperty(D)?
I=ta[D]:nsktzqy.hasOwnProperty(D)&&(I=nsktzqy[D]),w[nsyajtsqee][D]=I);t=nsqsjni.stringify(w);nsoednk.hasOwnProperty("pageModeConfig")&&!0===nsoednk.pageModeConfig.encodeData&&(t=nsihsc(t));for(d=0;d<nsoedn.length;d++)nsoedn[d].value=t}catch(eb){}}}function q(d){var k=d.key;return"undefined"!==typeof k&&"Unidentified"!==k&&null!==k?k:229!==d.keyCode?String.fromCharCode(d.keyCode):"NOP"}function u(d){var k=x(),t=C(Ca,k,[Z.length]);if(0===ia||d.length+t.length<=ia)return"";d=d.substring(0,ia-t.length);
var w=d.lastIndexOf(";");if(0>w)return"";R=k;return d.substring(0,w+1)+t+";"}function C(d,k,t){k-=R;1<ua&&(k=Math.round(k/ua));d=d+","+k.toString(16);if(null!=t&&0<t.length){d+=",";k=[];for(var w=0;w<t.length;w++)"number"===typeof t[w]?k.push(Math.round(t[w]).toString(16)):null!=t[w]&&k.push(t[w].toString());t=k.join(",");d+=t}return d}function z(){var d=[];for(var k=0;k<F.length;k++){var t=F[k];t.type&&t.type.match(H)&&(d.push(t.id),d.push(t.value.length))}d=d.join(",");g(Ma,[d])}function l(d){d||
(d=window.event);var k=null;d.target?k=d.target:d.srcElement&&(k=d.srcElement);3==k.nodeType&&(k=k.parentNode);if(d.keyCode)var t=d.keyCode;else d.which&&(t=d.which);var w=!1;d.which?w=3==d.which:d.button&&(w=2==d.button);var D=e(d),I={};I.a=d;I[J]=k;I.c=w;I.d=t;I.e=D.x;I.f=D.y;return I}function g(d,k){var t=x();if(null==R){va=R=Fa=t;var w=[nsihscpgi(),Na,ua];M=M+C("ncip",t,w)+";";R=t}M=M+C(d,t,k)+";";R=t;15E3<=t-va&&(M=M+C("ts",t,[t-Fa])+";",va=R=t);switch(d){case Ga:case Ha:case Oa:case ra:case wa:v(t);
break;default:2E3<t-Ia&&v(t)}}function h(d){for(var k=0;k<d.length;k++)if(0!==d[k])return!0;return!1}function m(){null!==T&&(clearInterval(T),T=0);null!==K&&"undefined"!==typeof xa[K+1]&&(K++,T=setInterval(B,xa[K]),ca.addCallback(function(){clearInterval(T)}),!1===S?(U=1,S={pos:da,time:x()}):U=0)}function v(d){Ia=d;M&&(d=window.ndsapi||(window.ndsapi={}),Z+=M,Y=u(Z),!0===G&&f(!1),M="",0<Y.length?d.setFormFieldData("ipr",Y):d.setFormFieldData("ipr",Z))}function y(d,k){var t,w=[];if(null===d||"undefined"===
typeof d||0===d.length)w=document.documentElement.getElementsByTagName("input");else if(("object"===typeof d||"function"===typeof d)&&"number"===typeof d.length){for(t=0;t<d.length;t++){var D=d[t];"string"===typeof D?(D=document.getElementById(D),"undefined"!==typeof D&&null!==D&&w.push(D)):"object"===typeof D&&null!==D&&w.push(D)}null!==F&&(w=w.concat(F))}d=[];for(t=0;t<w.length;t++)D=w[t],D.type&&D.type.match(H)&&(k||0!==D.offsetWidth||0!==D.offsetHeight)&&(d.push(D),p(D,nscchyl,Pa),p(D,nsktz,Qa),
p(D,nsxsswrsym,Ra),p(D,nsmnu,Sa),p(D,nsqsj,Ta));F=nstybx(d);p(document,nsmnuqjc,Ua);p(document,nsktzqytg,Va);p(document,nscchylse,Wa);p(window,nsnevfosjd,Xa);p(window,nsoednkcky,Ya)}function n(d,k,t){d=Math.round(d*Math.pow(10,k));if("undefined"===typeof t||!0===t)d/=Math.pow(10,k);return d}function r(d){if(!(J in d))return null;"string"===typeof d[J].id&&""!==d[J].id?d=d[J].id:"string"===typeof d[J].name&&""!==d[J].name?d=d[J].name:(d=Array.prototype.slice.call(F).indexOf(d[J]),d=0<=d?"ndiprinput"+
d:"");return d}function x(){return parseInt((new Date).getTime(),10)}function B(){var d=x();if(!1!==S){var k=Math.abs(da.x-S.pos.x)*ha,t=Math.abs(da.y-S.pos.y)*L,w=(d-S.time)/1E3,D=n(k/w,4,!0),I=n(t/w,4,!0);t=Math.sqrt(Math.pow(k,2)+Math.pow(t,2));k=n(t/w,4,!0);(null===ja||k<ja)&&0!==k&&(N=[D,I],ja=k);(null===ka||k>ka)&&0!==k&&(O=[D,I],ka=k);V+=k;W+=t;null!==ma&&(w=(k-ma)/w,(null===P||w<P)&&0!==w&&(P=w),(null===Q||w>Q)&&0!==w&&(Q=w),ea+=w);ma=k}0!==U&&0===U%fa[K]&&(w=0===na?0:d-na,V=n(V/fa[K],4,!1),
W=n(W,4,!1),D=0,0===w&&(D=-1),ea=n(ea/(fa[K]+D),4,!1),null===N&&null===O&&0===V&&0===W?g(wa,[w,fa[K],"NOP"]):(N[0]=n(N[0],4,!1).toString(16),N[1]=n(N[1],4,!1).toString(16),O[0]=n(O[0],4,!1).toString(16),O[1]=n(O[1],4,!1).toString(16),P=null!==P?n(P,4,!1):0,Q=null!==Q?n(Q,4,!1):0,g(wa,[w,fa[K],N[0]+" "+N[1],O[0]+" "+O[1],V,W,P,Q,ea])),ka=O=ja=N=null,W=V=0,Q=P=null,ea=0,na=d);S={pos:da,time:d};U>=Ja[K]&&m();U++}function p(d,k,t){attachEventListener(d,k,t,ca.addCallback)}var A=0,E=!1,G=!0,F=null,H=/^(text|password|email|url|search|tel)$/i,
L=1/window.screen.height,ha=1/window.screen.width,ca={addCallback:function(){},callAllCallbacks:function(){}},qa=!1,oa=0,X={},ia=0,la=25;nsihscp("ipr",{init:function(d){var k=window.ndsapi||(window.ndsapi={}),t=d.hasOwnProperty("fm")?d.fm:null;E=d.hasOwnProperty("bh")?d.bh:!1;ia=d.hasOwnProperty("tl")?d.tl:ia;la=d.il||la;A=0;F=null;L=1/window.screen.height;ha=1/window.screen.width;G=!0;oa=0;X={};ca.callAllCallbacks();ca=nds.common.createCallbackList();T=da=null;S=K=!1;U=0;xa=[100,200,2E3];Ja=[100,
300,150];fa=[10,50,30];na=0;ka=O=ja=N=null;W=V=0;Q=P=ma=null;ea=0;y(t,E);k.setFormFieldData("ipr","");k.setFormFieldData(nscchyls,"");a();z();(d=document.activeElement)&&-1<F.indexOf(d)&&(k={},k[J]=d,g(Ka,[r(k)]));b()},reinit:function(){f(!0);!0===nsoednk.eventModeEnabled&&(G=!1);a()},bind:function(d,k){y(k,E);z()},rebind:function(d,k){ca.callAllCallbacks();y(k,E);z();b()},clear:a,stop:function(){ca.callAllCallbacks();g(ra,[]);qa=!0}});var J="b",Pa=function(d){l(d);var k=ndoGetKeyTypeAndLocationIndicator(d);
d=q(d);"NOP"===d?d="N":(!1===X.hasOwnProperty(d)&&(X[d]=oa++),d=X[d]);d=[d];0!==k&&d.push(k);g(Za,d)},Qa=function(d){l(d);d=q(d);if("NOP"!==d)if(!0===X.hasOwnProperty(d)){var k=X[d];delete X[d];0<oa&&oa--;d=k}else d=null;k=[];null!==d&&"NOP"!==d&&k.push(d);g($a,k)},Ra=function(d){d=l(d);g(ab,[J in d&&"undefined"!==typeof d[J].value?d[J].value.length:null,r(d)]);g(Ka,[r(d)])},Sa=function(d){d=l(d);g(Ga,[r(d)])},Ua=function(d){d=l(d);g(Ha,[d.e,d.f,r(d)])},Ya=function(d){var k=[1E3*d.alpha,1E3*d.beta,
1E3*d.gamma];!0===c(ya,200)&&!0===h(k)&&(!0===d.absolute&&k.push(1),g(ya,k))},Xa=function(d){if(!0===c(za,200)&&null!==d.rotationRate){var k=[1E3*d.rotationRate.beta,1E3*d.rotationRate.gamma,1E3*d.rotationRate.alpha];!0===h(k)&&g(za,k)}!0===c(Aa,50)&&null!==d.accelerationIncludingGravity&&(k=[1E3*d.accelerationIncludingGravity.x,1E3*d.accelerationIncludingGravity.y,1E3*d.accelerationIncludingGravity.z],!0===h(k)&&g(Aa,k));!0===c(Ba,50)&&null!==d.acceleration&&(d=[1E3*d.acceleration.x,1E3*d.acceleration.y,
1E3*d.acceleration.z],!0===h(d)&&g(Ba,d))},Va=function(d){d=l(d);d.a&&d.a.touches&&d.a.touches[0]&&"undefined"!==typeof d.a.touches[0].pageX?g(La,[d.a.touches[0].pageX,d.a.touches[0].pageY,r(d)]):g(La,[-1,-1,r(d)])},Wa=function(d){da=e(d);null===T&&(K=-1,m());if(nsihscpgi()<A)return!1;A=nsihscpgi()+5;d=l(d);g(bb,[d.e,d.f,r(d)])},Ta=function(d){g(db,void 0)},da=null,T=null,K=!1,S=!1,U=0,xa=[100,200,2E3],Ja=[100,300,150],fa=[10,50,30],na=0,N=null,ja=null,O=null,ka=null,V=0,W=0,ma=null,P=null,Q=null,
ea=0,Ka="ff",Ga="fb",Za="kd",$a="ku",bb="mm",Ha="mc",La="te",Oa="fs",ab="kk",Ma="st",wa="mms",ra="so",Ca="tr",Aa="ac",za="gy",Ba="lac",ya="or",db="pe",Na=2,ua=1,Fa=null,R=null,Ia=null,va=null,M="",Z="",Y="",pa=x(),aa="",ba={};ba[Aa]=0;ba[za]=0;ba[Ba]=0;ba[ya]=0})();nds.ndeb="1.dev-1.0.x7yv6fs/KDVfTfj4n8BssQ\x3d\x3d.j915c9gbClPLf7y4v4OXFExFAcEERvCozYwxamuIuZ1ERvwaHTYH3xaMz70chPamf0cC9TuXGZdl6LZcQLaCGt4eXN71pgceClzd5ESyLgDbCxVyN/vCaqTZD07ug2wh";ndwts({"co":{"gzrq":false,"useNdx":true,"ndsidConfig":{"enable":false,"secure":false,"options":[]},"clientSideCookie":false,"initBindings":null,"initId":"","eventModeEnabled":false,"pageModeConfig":{"enable":true,"formbind":[],"inputFieldName":"nds-pmd","encodeData":true,"options":[],"wt":"1.w-481390.1.2.gELQO1qIwphs8W4qWNprNQ,,.QiHxtdnleEGRb6-E_ZIN0PvRb5U4C6EyF6oXMy-SCRDdcZ0Qn90Y8zx4KGJbUCostzyBMCQi41r5JCeL4qZ33SKTKUf5XKx0qKrj7nMVOhqp_JKstuoAh4F0znVRCo5AW-qmPlIw127vZw5qEvdG4wzeaPUoK39X8RLtRo1LlUXsQIwv1NBWf-Im5re5mxBCk4aWRF_Lj6XhD3l1lEEGSP1w_Ugd2LpFd7OHWGwjIv50YOHm36wrwsfuOKmhC713","requireWidgetToken":true}},"ml":{"id":[],"i":{"bi":"bi","ls":"ls"},"c":{"ua":"ua","bp":"bp","sr":"sr","didtz":"didtz","af":"af","wkr":"wkr","flv":"flv","fv":"fv","fa":"fa","hf":"hf","pl":"pl","ft":"ft","fc":"fc","fs":"fs","wg":"wg","bd":"bd","jsv":"jsv","p":"p","ipr":"ipr"},"pmd":{"bp":"bp","sr":"sr","didtz":"didtz","af":"af","wkr":"wkr","flv":"flv","fv":"fv","fa":"fa","hf":"hf","pl":"pl","ft":"ft","fc":"fc","fs":"fs","wg":"wg","fm":"fm","bd":"bd","jsv":"jsv","dit":"dit","ipr":"ipr","ic":"ic","wv":"wv"}},"wmd":{"ipr":{"fm":[],"lm":true,"bh":false,"tl":5000,"il":25},"wk":{"r":"test"},"di":{"rt":128,"ut":512,"ac":true},"af":{"e":false,"gtfs":"input[type=\"text\"],input[type=\"password\"]","rms":"input[name=\"remember-me\"]"}},"fd":{"ipr":"p","bi":"p"},"wc":"application\/javascript"})